name: Data Pipeline and Deployment

on:
  push:
    branches: [main]

jobs:
  data-cleaning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Clean Data
        run: python scripts/data_cleaning.py
      
      - name: Commit cleaned data
        run: |
          git add data/cleaned_data.csv
          git commit -m "Update cleaned data"
          git push

  train-model:
    runs-on: ubuntu-latest
    needs: data-cleaning
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Train Model
        run: python scripts/train_model.py
      
      - name: Commit model
        run: |
          git add scripts/churn_model.pkl
          git commit -m "Update trained model"
          git push

  deploy-api:
    runs-on: ubuntu-latest
    needs: train-model
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token $VERCEL_TOKEN
